### PR TITLE
added morgan

### LINKED ISSUE #1: add morgan logging
add advanced request logging using morgan

### PR DESCRIPTION
**Pull request by PranavGPR**
resolves #1

### CODE REVIEW

**Comment by KrishnaMoorthy12** [comment]
add logging functionality, not just package.

**Comment by PranavGPR** [comment]
gonna add functionality

**Comment by PranavGPR** [comment]
@KrishnaMoorthy12 check now

**Comment by PranavGPR** [comment]
Review this pull request and close this asap @KrishnaMoorthy12

**Review by KrishnaMoorthy12 — APPROVED** [review]
Good job.

**Pull request merged**
